version: '3.8'

services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-4.0-env
    volumes:
      - ../../data:/workspace/data
      - ../../src:/workspace/src
      - ../../notebooks:/workspace/notebooks
    ports:
      - "4040:4040"
      - "7077:7077"
      - "8080:8080"
    environment:
      - SPARK_MASTER_HOST=0.0.0.0
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_DRIVER_MEMORY=4g
      - SPARK_EXECUTOR_MEMORY=4g
      - SPARK_DRIVER_MAXRESULTSIZE=2g
    working_dir: /workspace
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 6G 